### ISSUE TITLE
Uncaught TypeError: event.target.getModel is not a function

### ISSUE THREAD

**Issue by MichelBiezunski** [fcrespo82/atom-markdown-table-formatter#30]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.6.2
**System**: Mac OS X 10.10.5
**Thrown From**: [markdown-table-formatter](https://github.com/fcrespo82/atom-markdown-table-formatter) package, v2.8.0

### Stack Trace

Uncaught TypeError: event.target.getModel is not a function

```
At /Users/michel/.atom/packages/markdown-table-formatter/lib/markdown-table-formatter.coffee:47

TypeError: event.target.getModel is not a function
    at atom-text-editor.<anonymous> (/Users/michel/.atom/packages/markdown-table-formatter/lib/markdown-table-formatter.coffee:47:47)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1013:28)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
```

### Commands

```
     -4:40 core:move-down (input.hidden-input)
  2x -4:39.5.0 core:move-up (input.hidden-input)
  3x -4:35 core:backspace (input.hidden-input)
     -4:33.3.0 autocomplete-plus:confirm (input.hidden-input)
  2x -4:33.1.0 editor:newline (input.hidden-input)
     -2:09.1.0 core:paste (input.hidden-input)
     -2:05.7.0 core:save (input.hidden-input)
     -1:51 editor:consolidate-selections (input.hidden-input)
     -1:51 core:cancel (input.hidden-input)
     -1:34.4.0 markdown-preview:toggle (input.hidden-input)
  3x -1:13.6.0 core:move-right (input.hidden-input)
  3x -1:10.9.0 core:save (input.hidden-input)
     -0:47 core:move-down (input.hidden-input)
     -0:41.7.0 core:save (input.hidden-input)
  2x -0:36.2.0 markdown-preview:toggle (input.hidden-input)
     -0:08.3.0 markdown-table-formatter:format (input.hidden-input)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-pylint",
      "linter-pep8",
      "linter-htmlhint",
      "linter-js-standard"
    ],
    "themes": [
      "atom-material-ui",
      "base16-tomorrow-light-theme"
    ]
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.4
atom-beautify, v0.29.2
atom-django, v0.3.2
atom-html-preview, v0.1.19
atom-material-ui, v1.2.10
atom-ternjs, v0.13.2
autocomplete-angular-material, v0.4.0
autocomplete-python, v1.7.2
color-picker, v2.1.1
django-templates, v0.5.0
linter, v1.11.4
linter-jshint, v2.1.0
linter-pylama, v0.2.9
linter-python-pep8, v0.2.0
linter-xmllint, v1.3.4
markdown-table-formatter, v2.8.0
markdown-themeable-pdf, v1.0.1
pdf-view, v0.50.0

# Dev
No dev packages
```

**Comment by fcrespo82** [comment]
Commit be682405206517a778334195be6c30d89ee247b0 should fix that.

In case not, please let me know.
